/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Fields */

#ifndef _Included_Fields
#define _Included_Fields
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Fields
 * Method:    accessFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Fields_accessFields
  (JNIEnv *, jobject);

/*
 * Class:     Fields
 * Method:    accessStrings
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Fields_accessStrings
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
