/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OneToOne1 */

#ifndef _Included_OneToOne1
#define _Included_OneToOne1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OneToOne1
 * Method:    atol
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_OneToOne1_atol
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
