/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Methods */

#ifndef _Included_Methods
#define _Included_Methods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Methods
 * Method:    accessConstructor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Methods_accessConstructor
  (JNIEnv *, jobject);

/*
 * Class:     Methods
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Methods_accessStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     Methods
 * Method:    accessInstanceMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Methods_accessInstanceMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
