/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Arrays */

#ifndef _Included_Arrays
#define _Included_Arrays
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Arrays
 * Method:    createIntArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_Arrays_createIntArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     Arrays
 * Method:    sumSmallArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Arrays_sumSmallArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Arrays
 * Method:    sumLargeArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Arrays_sumLargeArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Arrays
 * Method:    updateArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_Arrays_updateArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
