/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Strings */

#ifndef _Included_Strings
#define _Included_Strings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Strings
 * Method:    getSendMsg
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Strings_getSendMsg
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
