/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Calc */

#ifndef _Included_Calc
#define _Included_Calc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Calc
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calc_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Calc
 * Method:    div
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calc_div
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
