/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CatchThrow1 */

#ifndef _Included_CatchThrow1
#define _Included_CatchThrow1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CatchThrow1
 * Method:    catchException
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_CatchThrow1_catchException
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
