/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Arrays11 */

#ifndef _Included_Arrays11
#define _Included_Arrays11
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Arrays11
 * Method:    mulInt2DArray
 * Signature: ([[I[[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Arrays11_mulInt2DArray
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     Arrays11
 * Method:    mulScalarInt2DArray
 * Signature: ([[I[I)V
 */
JNIEXPORT void JNICALL Java_Arrays11_mulScalarInt2DArray
  (JNIEnv *, jobject, jobjectArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
