/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CatchThrow */

#ifndef _Included_CatchThrow
#define _Included_CatchThrow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CatchThrow
 * Method:    nativeThrow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CatchThrow_nativeThrow
  (JNIEnv *, jobject);

/*
 * Class:     CatchThrow
 * Method:    nativeThrowNew
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CatchThrow_nativeThrowNew
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
